from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.home,name='home'),
    path('signup/', views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('forgot/', views.forgot_password, name='forgot'),
    path('reset/<str:token>/', views.reset_password, name='reset'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('services/',views.services,name='services'),
    path('dashboard/',views.customer_dashboard,name='customer_dashboard'),
    path('request-pickup/',views.request_pickup,name='request_pickup'),
    path('my-request/',views.my_request,name='my_request'),
    path('payment/',views.customer_payment,name='customer_payment'),
    path('feedback/',views.feedback,name='feedback'),
    path('profile/',views.profile,name='profile'),
    path("logout/", views.logout_view, name="logout"),
    path('admin-dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('admin-profile/',views.admin_profile,name='admin_profile'),
    path('admin-user/',views.admin_user,name='admin_user'),
    path("delete-user/<int:id>/", views.delete_user, name="delete_user"),
    path('admin-pickups/',views.admin_pickups,name='admin_pickups'),
    path("admin-reports/", views.admin_reports, name="admin_reports"),
    path("download-report/<int:id>/", views.download_report, name="download_report"),
    path('admin-payments/',views.admin_payments,name='admin_payments'),
    path('agent-dashboard/',views.agent_dashboard,name='agent_dashboard'),
    path('assigned-pickups/',views.assigned_pickups,name='assigned_pickups'),
    path('agent-profile/',views.agent_profile,name='agent_profile'),
    path("verify-pickup/<int:id>/", views.verify_pickup, name="verify_pickup"),
    path("start-pickup/<int:id>/",views.start_pickup,name="start_pickup"),
    path("complete-pickup/<int:id>/",views.complete_pickup,name="complete_pickup"),
    path('hub-dashboard/',views.hub_dashboard,name='hub_dashboard'),
    path("received-waste/",views.received_waste,name="received_waste"),
    path("verify-waste/<int:id>/",views.verify_waste,name="verify_waste"),
    path("reject-waste/<int:id>/",views.reject_waste,name="reject_waste"),
    path("pickup-history/", views.pickup_history, name="pickup_history"),
    path("hub-verify/<int:id>/",views.hub_verify_waste,name="hub_verify"),
    path("hub-complete/<int:id>/",views.hub_complete_waste,name="hub_complete"),
    path("hub-report/", views.hub_report, name="hub_report"),
    path('hub-profile/',views.hub_profile,name='hub_profile'),
    path("add-user/",views.add_user,name="add_user"),
    path("edit-user/<int:id>/", views.edit_user, name="edit_user"),
    path("make-payment/<int:id>/", views.make_payment, name="make_payment"),
    path('send-otp/<int:payment_id>/', views.send_otp, name='send_otp'),
    path("payment-success/<int:id>/", views.payment_success, name="payment_success"),
    path("admin-salary/",views.admin_salary,name="admin_salary"),
    path("pay-salary/<int:id>/",views.pay_salary,name="pay_salary"),
    path("send-salary-otp/<int:salary_id>/",views.send_salary_otp,name="send_salary_otp"),
    path("salary-payment-success/<int:id>/",views.salary_payment_success,name="salary_payment_success"),
    path("agent-salary/", views.agent_salary, name="agent_salary"),
    path("hub-payment/", views.hub_make_payment, name="hub_payment"),
    path('hub-send-otp/', views.hub_send_otp, name='hub_send_otp'),
    path("hub-payment-verify/", views.hub_payment_verify, name="hub_payment_verify"),
    path("hub-history/", views.hub_history, name="hub_history"),
    path("admin-settlements/", views.admin_settlements, name="admin_settlements"),
    path("update-location/",views.update_agent_location,name="update_location"),
    path("agent-location/<int:agent_id>/",views.get_agent_location,name="agent_location"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)