# Generated by Django 5.2.1 on 2026-03-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_time', models.DateTimeField(blank=True, null=True)),
                ('delay_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_pickups', to='mainapp.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pickups', to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PickupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Collected', 'Collected'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Transferred', 'Transferred')], default='Collected', max_length=20)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pickup')),
                ('recycling_hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.user')),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ewaste')),
            ],
        ),
    ]
