# Generated by Django 5.2.1 on 2026-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_agent_payment_paymenttransaction_report_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuptransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
