# Generated by Django 5.2.1 on 2026-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_pickuptransaction_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewaste',
            name='category',
            field=models.CharField(default='Electronic', max_length=50),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_address',
            field=models.CharField(max_length=200),
        ),
    ]
