# Generated by Django 5.2.1 on 2026-03-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='data_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(max_length=50),
        ),
    ]
