# Generated by Django 5.2.1 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_report_generated_by_remove_report_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
