# Generated by Django 5.2.1 on 2026-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_report_report_id_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
