# Generated by Django 5.2.1 on 2026-03-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_report_format_alter_report_generated_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='total_pickups',
        ),
    ]
