# Generated by Django 5.2.1 on 2026-03-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_salary_total_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_report', to='mainapp.user'),
        ),
    ]
