# Generated by Django 5.2.1 on 2026-03-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_report_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
    ]
