# Generated by Django 5.2.1 on 2026-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_report_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Started', 'Started'), ('Verified', 'Verified'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
