# Generated by Django 5.2.1 on 2026-03-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_salary_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary_amount',
            new_name='amount',
        ),
    ]
