# Generated by Django 5.2.1 on 2026-03-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_salary_amount_salary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.area'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.zone'),
        ),
    ]
