# Generated by Django 5.2.1 on 2026-03-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_pickup_area_pickup_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('gateway', models.CharField(default='Mock', max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='mainapp.salary')),
            ],
        ),
    ]
